services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - devops_network

  server:
    build: ./server
    container_name: devops_server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/project-devops
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongodb
    networks:
      - devops_network

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    container_name: devops_client
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - devops_network

networks:
  devops_network:
    driver: bridge

volumes:
  mongodb_data:
